nome = input("Digite o nome do cliente : ")
vencimento = int(input("Digite o dia de vencimento : "))
mesdevencimento = input("Digite o mes de vencimento : ")
valordafatura = input("Digite o valor da fatura : ")
print ("Olá , ", nome ,"\n","A sua fatura com vencimento em ",vencimento, "de", mesdevencimento,"no valor de R$ ",valordafatura,"esta fechada.")